# @package _global_
module:
  _target_: emg2qwerty.conformer_lightning.ConformerDecoder
  in_features: 96  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [256]
  d_model: 128
  nhead: 4
  num_encoder_layers: 4
  num_decoder_layers: 4
  ff_expansion_factor: 2
  conv_kernel_size: 15
  conv_expansion_factor: 1
  dropout: 0.1

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [0, 0]  # No padding, [1800, 200]  # 900ms past context, 100ms future context
