hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${hydra.run.dir}
    subdir: job${hydra.job.num}_${hydra.job.override_dirname}
  launcher:
    submitit_folder: ${hydra.run.dir}/submitit_logs/%j
    timeout_min: 2880
    cpus_per_task: null
    gpus_per_node: ${trainer.devices}
    tasks_per_node: 1
    mem_gb: null
    nodes: ${trainer.num_nodes}
    name: ${hydra.job.name}
    stderr_to_stdout: false
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.LocalLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: RUN
  searchpath: []
  callbacks: {}
  output_subdir: hydra_configs
  overrides:
    hydra:
    - hydra.mode=RUN
    task:
    - trainer.devices=1
  job:
    name: emg2qwerty
    chdir: null
    override_dirname: trainer.devices=1
    id: ???
    num: ???
    config_name: bi_lstm
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys:
        - checkpoint
        - cluster
        - trainer.accelerator
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /Users/howardshu/Documents/GitHub/emg2qwerty
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /Users/howardshu/Documents/GitHub/emg2qwerty/config
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: /Users/howardshu/Documents/GitHub/emg2qwerty/logs/2025-03-13/13-44-49
    choices:
      cluster: local
      decoder: ctc_greedy
      lr_scheduler: testing_linear_warmup_cosine_annealing
      optimizer: adam
      model: bi_lstm_ctc
      transforms: base_log_spectrogram
      user: single_user
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: submitit_local
      hydra/output: default
  verbose: false
