in_features: 528
mlp_features:
- 256
hidden_size: 128
num_lstm_layers: 4
dropout: 0.1
tds_conv_encoder_block_channels:
- 16
- 16
tds_conv_encoder_kernel_width: 15
optimizer:
  _target_: torch.optim.Adam
  lr: 0.0003
  weight_decay: 1.0e-05
lr_scheduler:
  scheduler:
    _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
    warmup_epochs: 10
    max_epochs: 300
    warmup_start_lr: 1.0e-08
    eta_min: 1.0e-06
  interval: epoch
decoder:
  _target_: emg2qwerty.decoder.CTCGreedyDecoder
