user: triple_user
dataset:
  train:
  - user: 9456349
    session: 2020-08-13-1597355141-keystrokes
  - user: 9456349
    session: 2020-08-18-1597785842-keystrokes-09456349
  - user: 89335547
    session: 2021-07-21-1626916256-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-02-1622681518-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-03-1622766673-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-06-05-1622885888-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 89335547
    session: 2021-07-22-1627004019-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 75228805
    session: 2021-03-19-1616181237-keystrokes-dca-study@1-ce039945-b49a-44ea-b3d6-007dace1b7a3
  - user: 75228805
    session: 2021-03-20-1616269232-keystrokes-dca-study@1-ce039945-b49a-44ea-b3d6-007dace1b7a3
  - user: 75228805
    session: 2021-03-22-1616443154-keystrokes-dca-study@1-ce039945-b49a-44ea-b3d6-007dace1b7a3
  val:
  - user: 9456349
    session: 2020-08-13-1597354281-keystrokes
  - user: 9456349
    session: 2020-08-17-1597701568-keystrokes-09456349
  - user: 89335547
    session: 2021-06-02-1622681518-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 75228805
    session: 2021-03-23-1616514852-keystrokes-dca-study@1-ce039945-b49a-44ea-b3d6-007dace1b7a3
  test:
  - user: 75228805
    session: 2021-03-23-1616515853-keystrokes-dca-study@1-ce039945-b49a-44ea-b3d6-007dace1b7a3
  - user: 9456349
    session: 2020-08-13-1597354281-keystrokes
  - user: 89335547
    session: 2021-06-04-1622861066-keystrokes-dca-study@1-0efbe614-9ae6-4131-9192-4398359b4f5f
  - user: 75228805
    session: 2021-03-23-1616510910-keystrokes-dca-study@1-ce039945-b49a-44ea-b3d6-007dace1b7a3
  root: ${hydra:runtime.cwd}/data
to_tensor:
  _target_: emg2qwerty.transforms.ToTensor
  fields:
  - emg_left
  - emg_right
band_rotation:
  _target_: emg2qwerty.transforms.ForEach
  transform:
    _target_: emg2qwerty.transforms.RandomBandRotation
    offsets:
    - -1
    - 0
    - 1
temporal_jitter:
  _target_: emg2qwerty.transforms.TemporalAlignmentJitter
  max_offset: 120
logspec:
  _target_: emg2qwerty.transforms.LogSpectrogram
  n_fft: 64
  hop_length: 16
specaug:
  _target_: emg2qwerty.transforms.SpecAugment
  n_time_masks: 3
  time_mask_param: 25
  n_freq_masks: 2
  freq_mask_param: 4
transforms:
  train:
  - ${to_tensor}
  - ${band_rotation}
  - ${temporal_jitter}
  - ${logspec}
  - ${specaug}
  val:
  - ${to_tensor}
  - ${logspec}
  test: ${transforms.val}
module:
  _target_: emg2qwerty.lightning.TDSConvCTCModule
  in_features: 528
  mlp_features:
  - 384
  block_channels:
  - 24
  - 24
  - 24
  - 24
  kernel_width: 32
datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding:
  - 1800
  - 200
optimizer:
  _target_: torch.optim.Adam
  lr: ${lr}
  weight_decay: ${weight_decay}
lr_scheduler:
  scheduler:
    _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
    warmup_epochs: 10
    max_epochs: 300
    warmup_start_lr: 1.0e-08
    eta_min: 1.0e-06
  interval: epoch
decoder:
  _target_: emg2qwerty.decoder.CTCGreedyDecoder
batch_size: 32
callbacks:
- _target_: pytorch_lightning.callbacks.LearningRateMonitor
- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${hydra:runtime.output_dir}/checkpoints
  mode: ${monitor_mode}
  monitor: ${monitor_metric}
  save_last: true
  verbose: true
checkpoint: null
lr: 0.0001
monitor_metric: val/CER
monitor_mode: min
name: base_tds_conv_ctc
num_workers: 4
seed: 1501
train: true
trainer:
  accelerator: gpu
  default_root_dir: ${hydra:runtime.output_dir}
  devices: 1
  max_epochs: 50
  num_nodes: 1
weight_decay: 0
